add dev and reset switch to tel-setup

diff --git a/bootstrap/changes/bin/tel-setup b/bootstrap/changes/bin/tel-setup
--- a/bootstrap/changes/bin/tel-setup
+++ b/bootstrap/changes/bin/tel-setup
@@ -1,24 +1,39 @@
-#!/data/data/com.termux/files/usr/bin/sh
+#!/usr/bin/env bash
 error() {
 	printf "\033[0;%sm%s\033[0m\033[0;%sm%s\033[0m\n" "${WHITE}" "[TEL]: " "${RED}" "${1}"
 }
-if [ "$1" == '--reset' ] ; then
-	echo "removing installed flags"
-	rm -f ~/.tel/.installed
+remove_data(){
+	printf "\033[0;%sm%s\033[0m\033[0;%sm%s\033[0m\n" "${WHITE}" "[TEL]: " "${ORANGE}" "Removing old data..."
+	#rm -f ~/.tel/.installed
+	rm -rf ~/.tel
 	rm -rf ~/.oh-my-zsh
+	rm -f ~/.zshrc
+}
 
-elif [ "$1" == '-h' ] ; then
+if [ "$1" == '-h' ] ; then
 echo 'usage: tel-setup [OPTION]
-	--reset     = reset before install (you may lose data)'
+	--reset 	deletes all TEL data and installs most decent updates
+	--dev 		deletes all TEL data and downloads most decent dev updates'
 	exit 0
+elif [ "$1" == '--dev' ] ; then
+	printf "\033[0;%sm%s\033[0m\033[0;%sm%s\033[0m\n" "${WHITE}" "[TEL]: " "${GREEN}" "Dev version"
+	echo "Dev mode"
+	remove_data
+	branch='dev'
+elif [ "$1" == '--reset' ] ; then
+	printf "\033[0;%sm%s\033[0m\033[0;%sm%s\033[0m\n" "${WHITE}" "[TEL]: " "${GREEN}" "Resetting"
+	remove_data
+	branch='master'
+else
+	branch='master'
 fi
 
 if [ ! -f "~/.tel/.installed" ]; then
-	pkg install wget unzip coreutils -y 2>&1
+	pkg install wget unzip coreutils -y 2>&1 || error 'failed to fetch required setup utils'
 fi
 
 cd ~/../usr/
-wget https://github.com/t-e-l/tel/raw/master/bootstrap/changes.zip 2>&1
+wget https://github.com/t-e-l/tel/raw/$branch/bootstrap/changes.zip 2>&1 || error "failed to download update from $branch"
 unzip -o changes.zip 2>&1
 rm -f changes.zip
 chmod +x ~/../usr/bin/tel-setup
