tel-setup --update and improvements

diff --git a/bootstrap/changes/bin/tel-setup b/bootstrap/changes/bin/tel-setup
--- a/bootstrap/changes/bin/tel-setup
+++ b/bootstrap/changes/bin/tel-setup
@@ -2,43 +2,68 @@
 error() {
 	printf "\033[0;%sm%s\033[0m\033[0;%sm%s\033[0m\n" "${WHITE}" "[TEL]: " "${RED}" "${1}"
 }
-remove_data(){
-	printf "\033[0;%sm%s\033[0m\033[0;%sm%s\033[0m\n" "${WHITE}" "[TEL]: " "${ORANGE}" "Removing old data..."
-	#rm -f ~/.tel/.installed
+rm_tel_data(){
+	printf "\033[0;%sm%s\033[0m\033[0;%sm%s\033[0m\n" "${WHITE}" "[TEL]: " "${ORANGE}" " ! Warning ! this action will remove all TEL data from your device"
+	printf "\033[0;%sm%s\033[0m\033[0;%sm%s\033[0m\n" "${WHITE}" "[TEL]: " "${ORANGE}" "Are you sure you wish to continue? Y/N"
+	read -r user_reponse
+	if [ "$user_reponse" != 'y' ] || [ "$user_reponse" != 'Y' ]; then
+		error "User cancelled setup..." ; sleep 1 ; exit 1
+	fi
+	printf "\033[0;%sm%s\033[0m\033[0;%sm%s\033[0m\n" "${WHITE}" "[TEL]: " "${GREEN}" "Wiping data..."
 	rm -rf ~/.tel
+	rm -rf ~/.oh-my-zsh
+#	rm -f ~/.zshrc
+#	rm -f ~/.zlogin # these will be all be overwritten by a full install of setup after .installed flag is removed anyway
+#	rm -f ~/.aliases
+#	rm -f ~/.envvar
+#	rm -f ~/../usr/etc/motd
+}
+rm_user_data(){
+	printf "\033[0;%sm%s\033[0m\033[0;%sm%s\033[0m\n" "${WHITE}" "[TEL]: " "${ORANGE}" "Removing user data..."
 	rm -rf ~/.oh-my-zsh
 	rm -f ~/.zshrc
 	rm -f ~/.zlogin
+	rm -f ~/.aliases
 	rm -f ~/.envvar
+	rm -rf ~/.tel/configs
+	rm -rf ~/.tel/data
+	rm -rf ~/.config
+	rm -f ~/../usr/etc/motd
 }
+remove_tel_data='false'
+remove_user_data='false'
 
 if [ "$1" == '-h' ] || [ "$1" == '--help' ] ; then
-echo 'usage: tel-setup [OPTION]
-	--reset 	deletes all TEL data and installs most recent updates
-	--dev 		deletes all TEL data and downloads most recent developer version
-	--custom	deletes all TEL data and prompts for a custom branch name'
+	echo 'usage: tel-setup [OPTION]
+	--help 		display this help info
+	--update	get latest release updates
+	--reset 	setup release version (destructive)
+	--dev 		setup developer version (destructive)
+	--custom	setup custom version (destructive)'
 	exit 0
+elif [ "$1" == '--update' ] ; then
+	printf "\033[0;%sm%s\033[0m\033[0;%sm%s\033[0m\n" "${WHITE}" "[TEL]: " "${GREEN}" "Getting updates"
+	branch='master'
 elif [ "$1" == '--dev' ] ; then
-	printf "\033[0;%sm%s\033[0m\033[0;%sm%s\033[0m\n" "${WHITE}" "[TEL]: " "${GREEN}" "Dev version"
-	remove_data
+	printf "\033[0;%sm%s\033[0m\033[0;%sm%s\033[0m\n" "${WHITE}" "[TEL]: " "${GREEN}" "Getting developer version"
+	remove_tel_data='true'
 	branch='dev'
 elif [ "$1" == '--custom' ] ; then
-	printf "\033[0;%sm%s\033[0m\033[0;%sm%s\033[0m\n" "${WHITE}" "[TEL]: " "${ORANGE}" "Warning: You may lose TEL data setting up custom branch"
-	printf "\033[0;%sm%s\033[0m\033[0;%sm%s\033[0m\n" "${WHITE}" "[TEL]: " "${ORANGE}" "Are you sure you wish to continue?"
-	read -r user_reponse
-	if [ "$user_reponse" != 'Y' ] ; then
-		error "Exiting setup..."
-		exit 1
-	else
-		printf "\033[0;%sm%s\033[0m\033[0;%sm%s\033[0m\n" "${WHITE}" "[TEL]: " "${GREEN}" "Which branch do you want to setup?"
-		read -r branch
-		remove_data
-	fi
+	printf "\033[0;%sm%s\033[0m\033[0;%sm%s\033[0m\n" "${WHITE}" "[TEL]: " "${GREEN}" "Which branch do you want to setup? e.g: staging"
+	read -r branch
+	remove_tel_data='true'
+	printf "\033[0;%sm%s\033[0m\033[0;%sm%s\033[0m\n" "${WHITE}" "[TEL]: " "${GREEN}" "Getting $branch"
+	read -r branch
 elif [ "$1" == '--reset' ] ; then
 	printf "\033[0;%sm%s\033[0m\033[0;%sm%s\033[0m\n" "${WHITE}" "[TEL]: " "${GREEN}" "Resetting & getting latest version"
-	remove_data
+	remove_tel_data='true'
 	branch='master'
+elif [ -n "$1" ] ; then #user picked non option
+	error "Unrecognised input option..."
+	error "try 'tel-setup --help' to see availible options"
+	exit 1
 else
+	printf "\033[0;%sm%s\033[0m\033[0;%sm%s\033[0m\n" "${WHITE}" "[TEL]: " "${GREEN}" "Getting updates"
 	branch='master'
 fi
 
@@ -47,7 +72,9 @@ if [ ! -f "$HOME/.tel/.installed" ]; then
 fi
 
 cd ~/../usr/ || return
-wget https://github.com/t-e-l/tel/raw/$branch/bootstrap/changes.zip 2>&1 || error "failed to download update from $branch"
+wget https://github.com/t-e-l/tel/raw/$branch/bootstrap/changes.zip 2>&1 || error "failed to download update from $branch" && exit 1
+[[ "$remove_tel_data" == "true" ]] && rm_tel_data
+[[ "$remove_user_data" == "true" ]] && rm_user_data
 unzip -o changes.zip 2>&1
 rm -f changes.zip
 chmod +x ~/../usr/bin/tel-setup
